import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'

import {FaGithub} from "react-icons/fa"
import {FaLinkedin} from "react-icons/fa"
import { HiAcademicCap } from "react-icons/hi2";

function SocialLink({ icon: Icon, ...props }) {
  return (
    <Link className="group p-1" {...props}>
      <Icon className="h-6 w-6 fill-zinc-500 transition group-hover:fill-zinc-600 dark:fill-zinc-400 dark:group-hover:fill-zinc-300" />
    </Link>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Yun Gu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="h-screen grid content-center">
          <div className="grid place-content-center ">
            <div className="grid grid-cols-2 gap-2 place-items-end m-2 justify-center">
              <h1 className="inline-block align-baseline text-5xl">Hi, I&apos;m</h1>
              <h1 className="inline-block align-baseline justify-self-stretch text-7xl">Yun</h1>
            </div>
            <div className='p-1 grid place-items-center'>
              <h1 className="text-8xl m-2">UX Designer</h1>
              <h1 className="text-8xl m-2">Web Developer</h1>
            </div>
          </div>
          <div className="flex justify-center mt-1 ">
              <div className="m-2"><SocialLink
                href="https://github.com/YunaGu"
                aria-label="Follow on GitHub"
                icon={FaGithub}
              /></div>
               <div className="m-2"><SocialLink
                href="https://www.linkedin.com/in/yun-gu-2a0a58229/?trk=public-profile-join-page"
                aria-label="Follow on Linkedin"
                icon={FaLinkedin}
              /></div>
               <div className="m-2"><SocialLink
                href="./lib/YunGuCV.pdf"
                aria-label="Download CV"
                icon={HiAcademicCap}
              /></div>
            </div>
        </div>
      </main>
    </>
  )
}
